// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEt8oOxnPsxWdBNvoD2sbvDUJg3PpAo2g',
    appId: '1:606464343723:web:0727f17ce1e8b5333341ee',
    messagingSenderId: '606464343723',
    projectId: 'fir-series-3ff63',
    authDomain: 'fir-series-3ff63.firebaseapp.com',
    storageBucket: 'fir-series-3ff63.firebasestorage.app',
    measurementId: 'G-CLSDY1HTMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA90mP6uf3w--9f1QTuo76hc8WZo7PdC10',
    appId: '1:606464343723:android:6e8fbd391e026b453341ee',
    messagingSenderId: '606464343723',
    projectId: 'fir-series-3ff63',
    storageBucket: 'fir-series-3ff63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDBxaeieA0sgpzMyzx01AylogJNP8CneM',
    appId: '1:606464343723:ios:82b29c76437ca0083341ee',
    messagingSenderId: '606464343723',
    projectId: 'fir-series-3ff63',
    storageBucket: 'fir-series-3ff63.firebasestorage.app',
    iosBundleId: 'com.example.microwealth',
  );
}
